server:
  port: '8082'
spring:
  profiles: dev
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/library_db
    platform: postgres
    password: admin_library_2023
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Home of the Universal Library

